name: 'KodeKloud Giphy PR Comment by Neyam'
description: 'Add a Giphy comment to new Pull Request!'

inputs:
  github-token:
    description: Github Token
    required: true
  giphy-api-key:
    description: Giphy API Key
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "award"
  color: "green"